lugg/react-native-config

package.json

- Adding a repository field means that people finding the project on npm are able to find the github source code
- adding other fields that usually are good to have

add fields to package.json

---

README.md
android/src/main/java/com/lugg/ReactNativeConfig/ReactNativeConfigModule.java

for using applicationIdSuffix in different flavors or when applicationId is different from package name in AndroidManifest #14

Fix when applicationId ≠ package name

---

android/build.gradle

- compile react-native as shown here: https://github.com/facebook/react-native/blob/d344963123142a08de9d64d0c2d1294f8fcad8a6/local-cli/generator-android/templates/src/app/build.gradle#L131

use react-native from node_modules

---

ios/ReactNativeConfig/BuildDotenvConfig.ruby

Fixes https://github.com/luggit/react-native-config/issues/47.

Fix inconsistency in file path when using /tmp/envfile

---

README.md

Cut down some unnecessary setup instructions

---

android/dotenv.gradle

Some minor tweaks, now using a regexp adapted from npm's dotenv to extract key/val.

Fix android parsing

---

ios/ReactNativeConfig/ReactNativeConfig.h

See #71 and https://github.com/facebook/react-native/releases/tag/v0.40.0

update ios headers for react native 0.40

---

android/dotenv.gradle

This proposal is a nice solution for issue #56. `getCurrentFlavor()` has some issue with Gradle Sync in Android Studio.

Added defaultEnvFile config

---

index.d.ts

I faced an issue when I use Typescript with this project. So I think it's better if we included this simple definition file for Typescript in the project.

Add Typescript type definition file

---

README.md

Thanks for all the work on this!
From https://github.com/luggit/react-native-config/issues/24#issuecomment-309836788, seems like a few folks found it useful.

Add README note on testing with jest

---

ios/ReactNativeConfig/BuildDotenvConfig.ruby

fix CRLF/LF issue 201

---

ios/ReactNativeConfig.xcodeproj/project.pbxproj
react-native-config.podspec

[tvOS] Update podspec
[tvOS] Add tvOS target

Added tvOS paltform support

---

README.md

Fix error in README troubleshooting section

---

android/build.gradle

change this, then it work for Chinese user~

change google() before jcenter()

---

README.md

369 Update docs to include react-native-config-node

---

react-native-config.podspec

Resolves https://github.com/luggit/react-native-config/issues/391
Based on https://github.com/luggit/react-native-config/issues/391#issuecomment-571948199
Add correct output file.
Update input file to use correct root path.

Add ouput file to podspec

---

android/dotenv.gradle

https://github.com/luggit/react-native-config/issues/333

add support for android buildTypes or productFlavors name with numeric

---

android/dotenv.gradle
ios/ReactNativeConfig/ReactNativeConfig.m

Reverts luggit/react-native-config#284

Revert "Added rudimentary system environment variable support."

---

README.md

@luancurti @rafaelmaeuer thought it would be nice to add this to the readme since a lot of issues are being created about `info.plist`, which makes it harder to find the actual one with @rafaelmaeuer's solution :)

update readme: add point about accessing variables in info.plist

---

react-native-config.podspec

https://github.com/facebook/react-native/issues/29633#issuecomment-694187116

Fix React dependency to enable XCode 12 build

---

Example/android/build.gradle
Example/android/gradle/wrapper/gradle-wrapper.properties
android/build.gradle
android/dotenv.gradle

- Upgrade gradle plugin with 4.1.0
- Update Example with gradle plugin 4.1.0 and gradle wrapper 6.5.0 because of minimum support on gradle plugin

Support newest Android Gradle Plugin

---

package.json

fixes #581
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta

make react-native-windows peer dependency optional

---

README.md

Added note for the bundle release

Improvement and Update README.md

---

README.md

This was based on https://github.com/luggit/react-native-config/issues/184#issuecomment-1362939821

chore: added instructions for type declaration

---

README.md

By using RN-Integrate, extra steps are applied automatically like in Expo CNG. Also makes the project easily upgradable. More info at https://react-native-integrate.github.io/integrate/

docs: Add RN-Integrate suggestion
