lugg/react-native-config

- ios/ReactNativeConfig.xcodeproj/project.pbxproj
Hi @pedro!
I've found a fixed path on project.pbxproj that was preventing from compiling iOS projects ;)
> Fixes path for BuildDotenvConfig.ruby on project.pbxproj

- index.android.js
- index.ios.js
- index.js
- package.json
Hi,
Don't know if this interests you but I have been trying to test with mocha and having problems (as it doesn't understand react-native and therefore the platform files). Merging these two files seems to work for me and allows mocha to require them directly. This means I can mock out the library successfully.
Was wondering what your reasons where for keeping them apart?
Thanks,
> Merge together the index files for easier testing

- android/dotenv.gradle
Android resource strings cannot include `%` as-is (cf. http://stackoverflow.com/questions/4414389/android-xml-percent-symbol).
> Replace `%` with a double-escaped unicode value

- README.md
This pull request adds troubleshooting instructions to the Readme file for when Proguard causes React Native Config to fail due to the minification process when optimising release builds. 
As I could not figure out an automated way of applying the suggested change to the proguard file, I have added the Readme instructions so they may be manually performed, if needed.
Fixes #29
> Add Proguard troubleshooting instructions to Readme

- android/dotenv.gradle
- ios/ReactNativeConfig/BuildDotenvConfig.ruby
Prevents missing `.env` files from breaking both iOS & Android.
This is happening in our [Ignite project](https://github.com/infinitered/ignite) which is a boilerplate for React Native.  We want `.env` to live in `.gitignore` which means, we'd have to write a script to automatically generate this file.
Which is problematic because it wouldn't run on `git pull`.
Related:
https://github.com/luggit/react-native-config/issues/7
> Fix missing env

- README.md
- android/dotenv.gradle
Allows specifying the env files (when using different env files based on versions) in the build.gradle instead of needing to export an environment variable.  The advantage is that it only requires a change in the build.gradle instead of every place that calls ./gradlew install.  It still supports the environment variable approach to preserve compatibility.
Example usage in a `build.gradle`:
```
project.ext.envConfigFiles = [
debug: ".env.development",
release: ".env.production",
]
apply from: "../../node_modules/react-native/react.gradle"
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
```
Note: it's important that it is before the `apply from: `
> Add support for specifying custom env files in gradle

- index.js
If `.env` file is empty/non-existant this module will export `null` instead of as expected an empty object. That will crash apps using the way suggested in the docs; `Config.SOME_VAR`. In my app I want it to run with defaults straight from the source and then be able to override some values via the .env file.
> Default export to empty object

- README.md
- ios/ReactNativeConfig/BuildDotenvConfig.ruby
Add the ability to use config in the `Info.plist` file.  
Based on https://coderwall.com/p/euesdq/use-defined-values-in-info-plist
> [info.plist] Add support for using constants in the Info.plist

- README.md
Clarify that build names must be lowercase when specifying the env file in build.gradle.
Right now it does a comparison between the map specified in `build.gradle` and a lowercase version of the task that is run (example: `./gradlew installStagingRelease` would be "stagingrelease" which it would search for as the key in the map).  Alternatively we could a case-insensitive compare, but it requires re-creating the hashmap (with all lowercase keys) as there is no easy way to do a case-insensitive get() on a HashMap().
> Clarify that must use lowercase build names

- ios/ReactNativeConfig/BuildDotenvConfig.ruby
Addressing #97 
When parsing dotenv files, if there's any guide to follow, it's the defacto [npm dotenv project](https://www.npmjs.com/package/dotenv#rules)
> The parsing engine currently supports the following rules:
> * BASIC=basic becomes {BASIC: 'basic'}
> * empty lines are skipped
> * lines beginning with # are treated as comments
> * empty values become empty strings (EMPTY= becomes {EMPTY: ''})
> * single and double quoted values are escaped (SINGLE_QUOTE='quoted' becomes {SINGLE_QUOTE: "quoted"})
> * new lines are expanded if in double quotes (MULTILINE="new\nline" becomes
{MULTILINE: 'new
line'}
> * inner quotes are maintained (think JSON) (JSON={"foo": "bar"} becomes {JSON:"{\"foo\": \"bar\"}")
This PR implements a more sophisticated matching using a [regular …
> Support Dotenv with quotes and nested quotes

- Example/ios/Example.xcodeproj/project.pbxproj
- README.md
- ios/ReactNativeConfig/BuildDotenvConfig.ruby
- ios/ReactNativeConfig/ReactNativeConfig.h
Hi!
I needed to ammend this: CONFIGURATION_BUILD_DIR => BUILD_DIR
in order to support multitargetApplications in ios. The CONFIGURATION_BUILD_DIR resolves to:
build/Debug-iphoneos/GeneratedInfoPlistDotEnv.h
but imagine you have a watch app watch extenstion and ios today widget in other targets. They will for example resolve to:
build/Debug-watchos/GeneratedInfoPlistDotEnv.h
which produces build errors, this pr fixes that
> Support For Multi Target Applications

- ios/ReactNativeConfig.xcodeproj/project.pbxproj
- ios/ReactNativeConfig/ReactNativeConfig.h
Hi, thanks for the great module!
It works fine when building in Xcode myself, but when running Xcode build on my build server, it will fail because it does not find the included Ruby-script.
This is fixed by adding the ruby script as an input file in the build phase run script.
> Add input file to run script to fix build problems on server

- package.json
We are not able to install package via Cocoapods at the moment. The .podspec file is part of the code in repository, but it's not installed with package via `npm` or `yarn`
> Package: including .podspec file during package installation

- ios/ReactNativeConfig/BuildDotenvConfig.ruby
With support of quotes in 0.4.1, the ruby regex only supports uppercase alphabetic characters.  While lowercase characters are non-standard for ENV variables, they should still be supported.  Numbers obviously should, ex. 'M2_HOME=...'.
> Change dotenv pattern to support lowercase and numbers.

- android/dotenv.gradle
Use task names and not task requests args to figure out which env file to use.  The args and names should be the same.
> Fix for issue #56.  

- android/dotenv.gradle
- ios/ReactNativeConfig/BuildDotenvConfig.ruby
Being able to export variables in a `.env` file allows one to be able to source the file in bash scripts, which can be immensely helpful.  I've updated the regex to also check for an optional unmatched group `export\s+`.
I also added a bit of regex to remove quotes for android - I'm sure that regex could be better, but I needed something like it and it worked for me.
Lastly I updated the regex101 link in `ios/ReactNativeConfig/BuildDotenvConfig.ruby`
> Allow exported variables in .env

- android/src/main/java/com/lugg/ReactNativeConfig/ReactNativeConfigPackage.java
As of ReactNative version 0.47.0 a breaking (Android) change was introduced where it is no longer necessary to override 'createJSModules'.
See details [here](https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8).
> ReactNative 0.47.0 - Android Breaking change - Remove override of 'createJSModules'

- README.md
I was looking at using this for signingConfigs but found this line about not doing so. Thanks for putting that in there and saving me time. I wanted to emphasize it a little more to make it more obvious for others.
> Emphasize that variables are stored with your code

- ios/ReactNativeConfig/ReactNativeConfig.h
Fixes redefinition of RCTMethodInfo in RN 0.48+
> Change import priority of React/RCTBridgeModule.h

- android/dotenv.gradle
Fixed the regex - it caused syntax error in generated BuildConfig.java file when quotes were used in the `.env` file. `export VAR1="aa bb cc"` caused
```
/BuildConfig.java:15: error: unclosed string literal
public static final String VAR1 = "aa bb cc"";
^
1 error
```
> fixed Android dotenv.gradle quotes matching

- ios/ReactNativeConfig/BuildDotenvConfig.ruby
Found the treatment of whitespace a bit interesting, wasn't sure if it was intentional, but wanted to document it!
```
DOT_ENV=dotenv # => "dotenv"
#DOTENV=dotenv # => no match
DOT_ENV= asdf asf # => " asdf asf "
DOTENV='dot env' # => "dot env"
DOTENV="dot env" # => "dot env"
DOT_ENV='dotenv' # => "dotenv"
DOT_ENV="DotEnv" # => "DotEnv"
DOTENV="Dot\nEnv" # => "Dot\nEnv"
DOTENV="{"Dot":"Env"}" # => "{\"Dot\":\"Env\"}"
export DOTENV="dotenv" # => "dotenv"
DOTENV ="dot env" # => no match
DOTENV= "dot env" # => "dot env"
DOTENV = "dot env" # => no match
```
> Update regex examples to clarify treatment of spaces

- README.md
The cmd command have a space between the ENVFILE and the value so the ENVFILE doesn't change.
> update cmd command

- ios/ReactNativeConfig.xcodeproj/project.pbxproj
When react-native is installed using cocoapods xcode cannot find react headers for react-native-config. This PR adds to HEADER_SEARCH_PATHS to look at header files in the Pods. 
Since Cocoapods does not allow build scripts it's still a good idea to link react-native-config with react-native link and add support for projects that do use react native via cocoapods
> Add Pods Public Header path to HEADER_SEARCH_PATHS

- ios/ReactNativeConfig/ReactNativeConfig.m
After upgrading to RN 0.49 I get the following warning:
```
Module ReactNativeConfig requires main queue setup since it overrides constantsToExport but doesn't implement requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
```
This PR should fix that
> Add `requiresMainQueueSetup` to fix warning in RN 0.49+

- ios/ReactNativeConfig/BuildDotenvConfig.ruby
If i declare Chinese character become a value, when i run my app in xcode, it will fail and show the follow error message:
```
./ReactNativeConfig/BuildDotenvConfig.ruby:22:in `split': invalid byte sequence in US-ASCII (ArgumentError)
from ./ReactNativeConfig/BuildDotenvConfig.ruby:22:in `<main>'
```
So i add this two lines code to avoid this error.
```ruby
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8
```
now it works fine.
> Allow utf-8 character in config value

- android/dotenv.gradle
- ios/ReactNativeConfig/BuildDotenvConfig.ruby
This pull request is meant to address https://github.com/luggit/react-native-config/issues/135
In the case of utilizing this library with BuddyBuild, an **app:assemble** command will only set the environment variables once during the gradle build. This update will hook the task of setting the environment variable before a **generate buildConfig** task. This allows us to hook into each variant that is created in the project.
> dotenv.gradle: Set environment variables per variant buildConfig task, with .env fallback

- android/dotenv.gradle
Added an option to check for the "ENVFILE" var in the System properties, simply to allow more flexibility when running react-native-config directly from android studio with flavors
> Updated dotenv.gradle

- ios/ReactNativeConfig/BuildDotenvConfig.ruby
During my tests the ios custom env was never read because it was always reading the defaultEnvFile.
> Fixed config read always from default .env file

- package.json
I saw that you have a small file with ts definitions. Would be great to have it included in package.json.
> Include ts definitions in package.json

- README.md
After my experience setting up this library, I strongly recommend these changes.
1. Move Setup info close to the top so it's clear what's necessary.  From the current description, it appears that just importing the library is sufficient, since the reader is probably trying to read from the top and follow step-by-step.
2. Make it clearer that the .plist step is necessary
Thanks!
> Rearrange Readme so Setup steps are clear

- Example/android/app/build.gradle
- Example/android/build.gradle
- Example/android/gradle/wrapper/gradle-wrapper.properties
- android/build.gradle
> Updated gradle to v4.4 and gradle-plugin to v3.1.4

- android/dotenv.gradle
Closes #327
This is one solution using defalutEnvFile to avoid mismatching env setting by not included build variant string if the other task about build task calling dotenv.gradle. check #327.
> always set default value instead of .env

- ios/ReactNativeConfig/BuildXCConfig.rb
The problem is that `//` are treated as comments in a xcconfig file.
As a consequence, any config values that are urls like `https://google.com` will be interpreted as `https:` by xcode from the xcconfig file. 
This PR solves it by inserting an empty variable `$()` between the double slashes `//` ([see this stack Q&A](https://stackoverflow.com/questions/21317844/how-do-i-configure-full-urls-in-xcconfig-files)). The regex replace is done in `BuildXCConfig.rb`
Best regards,
Derk
> Resolving '//' in xcconfig values so that urls can be used

- ios/ReactNativeConfig/BuildDotenvConfig.rb
This should be ok as subsequent runs just overwrite that file anyhow...
closes https://github.com/bars0um/react-native-config/issues/1
Otherwise a race condition occurs / or possibly just an odd state where a second execution of the task during the same build finds no envfile
> Remove delete of envfile

- README.md
We started integrating Dexguard into our project and were noticing the build config was coming through empty. In addition to the existing ProGuard rule, it is necessary to preserve the resource representing the build config package name.
> Update docs to include Dexguard keep resource rule

- ios/ReactNativeConfig/ReadDotEnv.rb
Fix to allow spaces in .env file
> Support spaces in iOS .env file

- react-native-config.podspec
This removes a warning in Xcode that it's targeting below the minimum version. Also [React Native supports iOS 9.0 and above](https://github.com/facebook/react-native#-requirements).
> Set iOS deployment target to 9.0

- ios/ReactNativeConfig/BuildDotenvConfig.rb
As described in https://github.com/luggit/react-native-config/issues/391#issuecomment-632331803 this re-enables the possibility of preprocessing Info.plist to update environment-variables on the first build.
> create GeneratedInfoPlistDotEnv.h for Info.plist preprocessing

- .gitignore
- README.md
- android/src/main/java/com/lugg/ReactNativeConfig/ReactNativeConfigModule.java
- index.js
- ios/ReactNativeConfig.xcodeproj/project.pbxproj
- ios/ReactNativeConfig/ReactNativeConfig.h
- ios/ReactNativeConfig/ReactNativeConfig.m
- ios/ReactNativeConfig/ReactNativeConfigModule.h
- ios/ReactNativeConfig/ReactNativeConfigModule.m
I've split a module for two interfaces that allowed to use config service without the `react` dependency.
That will helps to use a module in an ios app extensions.
> [ios] App extensions support

- react-native-config.podspec
When output file already exist, the script is not ran, even when configuration has changed. This causes a bug when using ```react-native run-ios --scheme <scheme>``` with different configurations for different schemes, resulting in having old configuration in the ```Config``` object, while environment variables are set properly.
Cleaning build folder (or derived data) manually before build with changed configuration fixes this problem, but also causes a rebuild of all dependencies which may be much longer, depending on the size of the project (and obviously is error prone).
When the ```output_files``` section of the script does not contain path to the generated file, it is recreated for every build, thus forcing the pod to rebuild, and results in having a proper config, while extending …
> Fixed regenerating config on each build

- ios/ReactNativeConfig/ReadDotEnv.rb
When `/tmp/envfile` points to a file that does not exist, it was not possible to load the default .env file because `defaultEnvPath` was pointing to the parent directory of `envs_root`. Also, I'm not a Ruby developer so please correct me if I am wrong, but I think line 39 is useless since `raw` will never be defined defined at that point.
> Fix incorrect default env path on iOS

- android/dotenv.gradle
fix " No signature of method: com.android.build.gradle.internal.variant.ApplicationVariantData.getVariantConfiguration() is applicable for argument types: () values: []" with gradle 4.0.1
> Fix deprecation with gradle 4.0.1

- index.js
The types definition (`index.d.ts`) explicitly says that the library can be used with a default import or a named import:
```
import Config from "react-native-config";
import { Config } from "react-native-config";
```
However, in the `index.js` file there's no named export, only the default export is available
cc. @pedro @luancurti
> Fix named import

- android/dotenv.gradle
- ios/ReactNativeConfig/ReactNativeConfig.m
**Note:** This is WIP and I definitely need some help on making this work the way most people would expect.
To really follow 12-factor, we need to be able to use environment variables at compile-time. I think what I have might just work on android, since it's in the gradle file, and iOS might just need to be documented, but I'd really like some other eyes of people who are way smarter than me.
Related to my issue, #271
> Added rudimentary system environment variable support.

- .gitignore
- README.md
- package.json
- react-native-config.podspec
The current podspec lists `React` as a dependency. This causes `RCTLinking` to be built (among other deps).
This can be problematic when working on an iOS 14 Widget that needs to share config variables since WidgetKit, and other extensions, do not allow certain functionality used in `RCTLinking`.
Separating into subspecs gives the consumer of `react-native-config` the option to pick what dependencies are built by their pod target
> Add subspec for iOS extensions without React

- android/build.gradle
We're depending on a version of the Android Gradle plugin higher than 3, so we don't need to specify a buildToolsVersion. Trying to grab this value from the root project, in a project that also doesn't specify it, would fail. Since the only reason we were doing the fetch was to specify our own buildToolsVersion, I think we can safely remove it.
> Don't specify buildToolsVersion on Android

- README.md
There's a comment as part of the review of pull request #281 by @danielwinkler that the build pre-action for iOS should copy the .env.staging (or whatever) file to ${PROJECT_DIR}/../.env, which turns out to be correct.  This change updates the README to reflect that (and also addresses his other comment about the second reference to /tmp/envfile).
@maharjanaman also mentioned on that pull request a problem with the script, and I believe that was from not having a "Provide build settings from" selection, so I added a comment about that, as well.
> Update README.md, correct iOS build pre-action

- android/dotenv.gradle
`getCurrentFlavor` is returning flavor in lower case but `loadDotEnv` just compare flavor with the key in `envConfigFiles` directly
Example:
If the flavor named as `tempRelease`, `getCurrentFlavor` will return `temprelease` and the comparison will be failed
> Fix flavor matching in dotenv.gradle

- README.md
Update readme file to suggest that autolinking is available for newer versions of React Native.
> Update readme: note on autolinking availability

- .github/workflows/windows-ci.yml
By mistake, I've left the `on: [watch]` int the workflow .yml file. I used that when developing, to trigger the CI run every time I've stared the repo.
This fixes this by changing it to `on: [pull_request]` which will correctly make the CI run on each new PR.
> Change the trigger for the Windows CI

- README.md
Small update to the doc to take into account that `PROJECT_DIR` may contain spaces and should be "escaped" so that the cp works in those cases.
I had the issue on my project where it worked well locally and failed in the CI because the CI had a space in PROJECT_DIR.
Since like me most people will copy paste the `cp` line from the readme it's worthwhile updating it so less people get this issue
> docs: escape cp for PROJECT_DIR with spaces

- README.md
The way matching is done can lead to unexpected results that can be difficult to troubleshoot.
I found this out the hard way with my own `debugProd` build variant alongside a `debug` one...
> add important caveat for android gradle env config

- ios/ReactNativeConfig/ReadDotEnv.rb
As noted in #522, .env files with blank lines or comments are no longer being ignored. This PR updates that. HTH!
> Ignore empty lines and comments in env files

- README.md
Added instruction to share new scheme on iOS in the [Different environment](https://github.com/luggit/react-native-config#ios-1) section.
Without this checkbox checked, the `xcsheme` file is not created and you won't be able to share it in your version control system.
> Updated REAMDE.md

- README.md
I miss read to use `app-id.XML` for default config.
How about to change `YOUR_PACKAGE_NAME_IN_ANDROIDMANIFEST.XML` to `YOUR_PACKAGE_NAME_IN_ANDROIDMANIFEST_XML`.
Related comment:
https://github.com/luggit/react-native-config/issues/170#issuecomment-796733674
> Change xml style to mention package name

- README.md
This library generates code using [Ruby script `ReadDotEnv.rb`](https://github.com/luggit/react-native-config/blob/v1.4.2/ios/ReactNativeConfig/ReadDotEnv.rb) which reads `ENVFILE` from the environment variables. The script is executed during the CocoaPods library build phase.
With [`pod_install` hook](https://guides.cocoapods.org/syntax/podfile.html#post_install) you can set custom build settings of CocoaPods libraries. Since Xcode exposes all build settings to the environment variables, this is the best place to set `ENVFILE`. You may also access to the build configurations so you can set different envfiles per build configurations.
(I'm using Debug, Development, Production build configurations)
- #281
> Add an instruction to configure different envfiles per build settings using Podfile

- windows/RNCConfig/RNCConfig.vcxproj
- windows/RNCConfig61/RNCConfig61.vcxproj
Fixes [#606](https://github.com/luggit/react-native-config/issues/606)
Replace macro of msbuild in project file.
| OS      | Implemented |
| ------- | :---------: |
| Windows |    ✅     |
> fix(windows): react-native-config don't work with apps in RNW v0.64

- README.md
I think this part was incorrectly highlighted making it look like that part is under the `windows` portion which is confusing.
> Used correct heading

- ios/ReactNativeConfig/BuildDotenvConfig.rb
BuildDotenvConfig.rb generates GeneratedInfoPlistDotEnv.h with old prefix RNC that isnt used anymore
Fixes #645 
Fixes #601
> fix: remove old prefix RNC

- README.md
Before [this release](https://github.com/luggit/react-native-config/releases/tag/v1.5.0) the files were renamed from`ReactNativeConfig.ReactNativeConfigPackage` to `RNCConfig.RNCConfigPackage`.
Generating the error:
```
Note: Recompile with -Xlint:deprecation for details.
/Users/marcelxsilva/Documents/projects/<NAME PROJECT>/android/app/src/main/java/com/<NAME PROJECT>/app/MainApplication.java:10: error: package com.lugg.ReactNativeConfig does not exist
import com.lugg.ReactNativeConfig.ReactNativeConfigPackage;
```
Basically update the readme to the correct import, after change builded with success.
> [FIX] - Documentation readme import lib

- react-native-config.podspec
Locally I can build my app just fine, but when I do:
```
rm -rf node_modules && yarn install && yarn ios-install # (cocoapods)
```
the subsequent builds fail, and the only way they succeed again is if I clear the DerivedData folder before building.
This is the output when I build after nuking my node_modules folder:
```
The following build commands failed:
CompileC /Users/abejfehr/Library/Developer/Xcode/DerivedData/MyApp-abcd1234/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-config.build/Objects-normal/x86_64/ReactNativeConfig.o /Users/abejfehr/my-app/node_modules/react-native-config/ios/ReactNativeConfig/ReactNativeConfig.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-config' from project 'Pods')
```
So this …
> Add GeneratedDotEnv.m as an output file

- README.md
- react-native-config.podspec
Minor tweaks to make things work with [react-native-macos](https://github.com/microsoft/react-native-macos)
> feat: macOS support

- package.json
- react-native-config.podspec
Resolves #804 by only specifying a visionos deployment target if visionos is supported by the user's cocoapods version.
> Make visionos optional

- react-native-config.podspec
As the .env file could be anywhere (monorepo etc) specifying a specific .env file path won't work and knowing how important it is to have .env in sync, I think running this script on every build makes sense
Fixes issues [692](https://github.com/lugg/react-native-config/issues/692) and [591](https://github.com/lugg/react-native-config/issues/591)
> fix(ios): always run script

- windows/RNCConfig/RNCConfig.vcxproj
In RNW .72, we bump WinUI from 2.7 to 2.8 which targets a higher TargetPlatformMinVersion. This PR bumps the WindowsTargetPlatformMinVersion to the correct version for RNW .72
>  fix: windows bump WindowsTargetPlatformMinVersion 
